AppDirect/service-integration-sdk

.travis.yml, pom.xml
JIRA ticket: https://appdirect.jira.com/browse/PI-9411
=> prepare for open-sourcing the project

.travis.yml, pom.xml, settings.xml
=> update to automatically deploy tags

pom.xml
releasing a version to test if sources are published
=> releasing 1.21

.travis.yml, pom.xml
Relates to https://github.com/AppDirect/service-integration-sdk/issues/81
(cherry picked from commit a0e8e3b)
=> Add javadoc generation on deployment

pom.xml
=> version 1.25

pom.xml
=> Changing the version to a stable version

pom.xml
=> Bumping release

pom.xml, src/main/java/com/appdirect/sdk/appmarket/usersync/UserSyncApiClient.java
=> Fixing javadoc

pom.xml
Updating the Spring Boot version to the latest version
=> bump spring boot version

.travis.yml, src/script/build_project.sh, src/script/publish_build_artifacts.sh, src/script/sync_bintray_to_maven_central.sh
https://appdirect.jira.com/browse/PI-10058 
Automatic syncing to Maven Central on deploy
NB!
In order for this to be functional, we need to add the following encrypted environment vars to the build settings in Travis:
* SONAR_USER -> Sonar username that can publish
* SONAR_USER_PASSWORD -> Password for the sonar user
=> Added a script for uploading binaries to Maven Central and ensured it is called after deploy

.travis.yml, src/script/build_project.sh, src/script/publish_build_artifacts.sh, src/script/sync_bintray_to_maven_central.sh
Attempting to resolve problems with deployment
=> Fixing script problems

src/script/publish_build_artifacts.sh
Version of deployed artifacts is resolved dynamically
=> dyn version

pom.xml, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventClient.java, src/main/java/com/appdirect/sdk/appmarket/events/EventInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrder.java, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java, src/main/java/com/appdirect/sdk/appmarket/saml/Certificate.java, src/main/java/com/appdirect/sdk/appmarket/saml/SamlRelyingPartyAttribute.java, src/main/java/com/appdirect/sdk/appmarket/saml/ServiceProviderInformation.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventClientTest.java, src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderTest.java
JIRA ticket: https://appdirect.jira.com/browse/PI-6985
=> Pi 6985 sso support

src/main/java/com/appdirect/sdk/appmarket/events/APIResult.java, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketCommunicationConfiguration.java, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventClient.java, src/main/java/com/appdirect/sdk/web/config/JacksonConfiguration.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventClientITTest.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventClientTest.java, src/test/java/com/appdirect/sdk/feature/CanDispatchSubscriptionOrderIntegrationTest.java, src/test/java/com/appdirect/sdk/feature/CanValidateCustomerDataIntegrationTest.java, src/test/java/com/appdirect/sdk/feature/DefaultHandlersIntegrationTest.java, src/test/java/com/appdirect/sdk/feature/ErrorHandlingIntegrationTest.java, src/test/resources/resolutionCallbacks/success.json, src/test/resources/resolutionCallbacks/unknown_error.json
Fix for https://github.com/AppDirect/service-integration-sdk/issues/118
=> PI-10221_failed_resolving_event

src/main/java/com/appdirect/sdk/appmarket/events/AddonInstanceInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClient.java, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketCommunicationConfiguration.java, src/main/java/com/appdirect/sdk/appmarket/events/Usage.java, src/main/java/com/appdirect/sdk/appmarket/events/UsageBean.java, src/main/java/com/appdirect/sdk/exception/ReportUsageException.java, src/main/java/com/appdirect/sdk/web/exception/ReportUsageApiExceptionHandler.java, src/main/java/com/appdirect/sdk/web/oauth/ReportUsageRestTemplateFactoryImpl.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClientITTest.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClientTest.java, src/test/java/com/appdirect/sdk/web/exception/ReportUsageApiExceptionHandlerTest.java, src/test/resources/events/usage-report-bill-request.json, src/test/resources/resolutionCallbacks/request_payload_billing_api.json
Issue #125: Report Usage to MP
JIRA ticket: [PI-10039](https://appdirect.jira.com/browse/PI-10039)
Update to handle the usage reports sent to mp according to @juan-blasco 's [tech design](https://appdirect.jira.com/wiki/display/PI/Integration+Service+SDK+-+Report+Usage)
=> Issue #125: Report Usage to MP

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClient.java
Resolving conflicts that don't allow a proper release.
=> Updating Javadoc

src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionChange.java, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionChangeEventParser.java, src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionChangeEventParserTest.java
[PI-11118](https://appdirect.jira.com/browse/PI-11118)
This PR is to add eventInfo > Payload > Configuration to SubscriptionChange object.
=> PI-11118 : Add "Payload.Configuration" object in subscriptionChange object

.travis.yml, src/script/publish_build_artifacts.sh
=> fix release process

src/script/publish_build_artifacts.sh
=> try to resolve the maven central deployment issue #137

src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrder.java, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java, src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParserTest.java, src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderTest.java
=> Revert "PI-12313 adding AccountInfo to SubscriptionOrder. (#147)"

src/main/java/com/appdirect/sdk/ConnectorSdkConfiguration.java, src/main/java/com/appdirect/sdk/web/config/MvcConfiguration.java, src/test/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipControllerIntegrationTest.java, src/test/java/com/appdirect/sdk/feature/sample_connector/full/configuration/FullConnectorDomainDnsOwnershipVerificationConfiguration.java, src/test/java/com/appdirect/sdk/support/FakeAppmarket.java
JIRA ticket: https://appdirect.jira.com/browse/PI-12150
We needed to configure Spring to stop truncating domains in the URL.
@hooriak @davidchau
=> Allow having a domain as path parameter

README.md, pom.xml, src/main/java/com/appdirect/sdk/security/configuration/model/RoleMapping.java, src/main/java/com/appdirect/sdk/security/exception/RoleMappingException.java, src/main/java/com/appdirect/sdk/security/openid/CustomAxFetchListFactory.java, src/main/java/com/appdirect/sdk/security/openid/CustomOpenIdConsumer.java, src/main/java/com/appdirect/sdk/security/openid/configuration/OpenIdSsoConfiguration.java, src/main/java/com/appdirect/sdk/security/openid/model/OpenIdUserDetails.java, src/main/java/com/appdirect/sdk/security/openid/service/CustomUserDetailsService.java, src/main/java/com/appdirect/sdk/security/utils/RoleMapper.java, src/test/java/com/appdirect/sdk/feature/sample_connector/full/FullConnector.java, src/test/java/com/appdirect/sdk/security/openid/CustomAxFetchListFactoryTest.java, src/test/java/com/appdirect/sdk/security/openid/CustomUserDetailsServiceTest.java, src/test/java/com/appdirect/sdk/security/utils/RoleMapperTest.java, src/test/resources/application.yml
=> OpenId Connect Feature

src/main/java/com/appdirect/sdk/appmarket/events/PricingUnit.java
=> Add Employee Pricing Unit

src/main/java/com/appdirect/sdk/appmarket/events/PricingUnit.java
=> Adding Instance as Pricing Unit

src/main/java/com/appdirect/sdk/appmarket/domain/CNameDnsRecord.java, src/main/java/com/appdirect/sdk/appmarket/domain/DnsRecords.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsOwnershipVerificationConfiguration.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsVerificationInfoHandler.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipController.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainServiceConfigurationHandler.java, src/main/java/com/appdirect/sdk/appmarket/domain/MxDnsRecord.java, src/main/java/com/appdirect/sdk/appmarket/domain/SrvDnsRecord.java, src/test/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipControllerTest.java, src/test/java/com/appdirect/sdk/feature/CanVerifyDomainsWhenModuleImportedIntegrationTest.java, src/test/java/com/appdirect/sdk/feature/sample_connector/full/configuration/FullConnectorDomainDnsOwnershipVerificationConfiguration.java
=> Modify Ownership proof endpoint to support service config

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClient.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClientITTest.java, src/test/java/com/appdirect/sdk/appmarket/events/AppmarketBillingClientTest.java
JIRA ticket:
Added async parameter to avoid concurrent modifications  of the POs.
=> Add async parameter to avoid concurrent modifications

.github/PULL_REQUEST_TEMPLATE.md, src/main/java/com/appdirect/sdk/vendorrequiredfields/VendorRequiredFieldConfiguration.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/VendorRequiredFieldController.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/VendorRequiredFieldHandler.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/converter/FlowTypeConverter.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/converter/OperationTypeConverter.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/FieldType.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/FlowType.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/Form.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/Level.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/OperationType.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/VendorRequiredField.java, src/main/java/com/appdirect/sdk/vendorrequiredfields/model/VendorRequiredFieldResponse.java
=> PI-14967: [VRF] Create controller + basic entities on SDK 

src/main/java/com/appdirect/sdk/vendorFields/controller/VendorFieldValidationController.java, src/main/java/com/appdirect/sdk/vendorFields/model/VendorFieldsValidationRequest.java, src/main/java/com/appdirect/sdk/vendorFields/model/VendorFieldsValidationResponse.java
Added applicationIdentifier field on VendorFieldValidationRequest for the VV API
=> PR-15192: Added applicationIdentifier field

src/main/java/com/appdirect/sdk/meteredusage/model/UsageItem.java, src/test/java/com/appdirect/sdk/meteredusage/mother/UsageItemMother.java, src/test/java/com/appdirect/sdk/utils/ConstantUtils.java
Changed Data Types used for new Client on SDK to consume Metered Usage V2 API.
=> Changed UsageItem attributes types

.travis.yml, src/main/java/com/appdirect/sdk/appmarket/events/OrderInfo.java
Added custom Attributes to Order Info.
=> PI-16307: added custom attributes to Order Info

src/main/java/com/appdirect/sdk/appmarket/events/OrderInfo.java, src/main/java/com/appdirect/sdk/meteredusage/model/CustomAttribute.java
Fields are not being mapped due to wrong names, they should be corrected to match the structure sent from the MP.
=> PI-16366: changed custom Attribute in order info

src/main/java/com/appdirect/sdk/meteredusage/model/UsageItem.java
=> PI-16558: fixed date format pattern

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketCommunicationConfiguration.java, src/main/java/com/appdirect/sdk/meteredusage/config/OAuth1RetrofitWrapper.java, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientService.java, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceImpl.java, src/test/java/com/appdirect/sdk/meteredusage/MeteredUsageApiClientServiceTest.java, src/test/java/com/appdirect/sdk/meteredusage/config/OAuth1RetrofitWrapperTest.java
- This PR changes the `baseUrl` logic so that it can be set dynamically for the API calls.
=> PI-16686: Changed url to be dynamic when creating the OAuth1RetrofitWrapper

src/main/java/com/appdirect/sdk/vendorFields/model/Form.java
- Adding `title` attribute to `Form` entity.
=> PI-16879: Adding title attribute to vendorFields Form entity

pom.xml, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientService.java, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceImpl.java, src/test/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceTest.java
Add "Secret" as a new parameter to MeteredUsageAPIClient
=> PI-16966: Add "Secret" as a new parameter to MeteredUsageAPIClient

pom.xml, src/main/java/com/appdirect/sdk/meteredusage/config/OAuth1RetrofitWrapper.java
This PR implements optional tracing in MeteredUsageApi.
=> PI-16595: Implementing tracing for outbound calls in MeteredUsageApi

src/main/java/com/appdirect/sdk/meteredusage/model/MeteredUsageRequest.java, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientService.java, src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceImpl.java, src/test/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceTest.java, src/test/java/com/appdirect/sdk/utils/ConstantUtils.java
In order to add source type field in metered usage v2 request we need to do these changes in SDK. 
=> PI-17473: Added sourceType field in metered usage request

src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceImpl.java, src/test/java/com/appdirect/sdk/meteredusage/mother/MeteredUsageItemMother.java, src/test/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceTest.java
This PR replaces all appearances of com.google.inject.internal.Lists.newArraylist(...) with Collections.singletonList(...) as that class was removed from newer versions of Google Guice, which are being used by the connectors.
=> PI-17835: Removing all appearances of Lists.newArrayList(...)

src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java
=> PI-17312: Added Error treatment in catch

src/main/java/com/appdirect/sdk/appmarket/events/OrderInfo.java
Add discountCode attribute in OrderInfo class.
=> PI-18205 [SDK] Add new discount field to SDK

src/main/java/com/appdirect/sdk/appmarket/events/CompanyInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/EventWithContext.java, src/main/java/com/appdirect/sdk/appmarket/events/EventWithContextWithConfiguration.java, src/main/java/com/appdirect/sdk/appmarket/events/FreeTrialInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/OrderInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/OrderItemInfo.java, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrder.java, src/main/java/com/appdirect/sdk/appmarket/events/UserInfo.java, src/main/java/com/appdirect/sdk/meteredusage/model/CustomAttribute.java
Added Serializable and Builder to SubscriptionOrder event.
=> PI-18753: Added Serializable and Builder to SubscriptionOrder event

src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldV2.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java
=> PI-20429 Add visible field to RFS V2

src/main/java/com/appdirect/sdk/vendorFields/configuration/VendorFieldsConfiguration.java, src/main/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldController.java, src/main/java/com/appdirect/sdk/vendorFields/handler/v2/VendorRequiredFieldHandler.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java
=> PI-20429 Add new parameter to rfs v2

src/main/java/com/appdirect/sdk/vendorFields/configuration/VendorFieldsConfiguration.java, src/main/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldController.java, src/main/java/com/appdirect/sdk/vendorFields/handler/v2/VendorRequiredFieldHandler.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java
This reverts commit 875b5823ebcb7cc948d7cb8abaa251a6c4b4e2f2, reversing
changes made to 973ef3815a6f708363a5c3ecd90facaafb6dd80c.
=> Revert "Merge pull request #228 from wilsonchingg/PI-20429-2"

src/main/java/com/appdirect/sdk/utils/LocaleHelper.java, src/test/java/com/appdirect/sdk/utils/LocaleHelperTest.java
=> PI-20429 Move ISO convertor logic to service-integration-sdk

src/main/java/com/appdirect/sdk/vendorFields/model/v2/FieldTypeV2.java
Dummy change to get new version of SDK.
=> Dummy change for new version

src/main/java/com/appdirect/sdk/web/oauth/BasicAuthRestTemplate.java, src/main/java/com/appdirect/sdk/web/oauth/DefaultRestTemplateFactoryImpl.java, src/main/java/com/appdirect/sdk/web/oauth/ReportUsageRestTemplateFactoryImpl.java, src/main/java/com/appdirect/sdk/web/oauth/RestTemplateFactory.java, src/main/java/com/appdirect/sdk/web/oauth/UserSyncRestTemplateFactoryImpl.java
we need to have support for RestTemplate with basic authentication in SDK
this is the POC to use restTemplate with basic authentication
Dev Testing
=> PI-21845  RestTemplate with Basic Authentication-POC

src/main/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipController.java, src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventController.java, src/main/java/com/appdirect/sdk/appmarket/migration/AppmarketMigrationController.java, src/main/java/com/appdirect/sdk/appmarket/restrictions/RestrictionController.java, src/main/java/com/appdirect/sdk/web/oauth/OAuth2FeatureFlagSupplierImpl.java
=> PI-21829 Added v2 endpoints for oAuth2

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventService.java
Updating event logger to log applicationUuid
=> Updating Event logger 

src/test/java/com/appdirect/sdk/feature/sample_connector/full/FullConnector.java, src/test/java/com/appdirect/sdk/feature/sample_connector/minimal/MinimalConnector.java
- Added Bean in Connector Classes For Test
=> PI-21796_1 :Added Bean in Connector Classes For Test

src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsOwnershipVerificationConfiguration.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipController.java, src/main/java/com/appdirect/sdk/appmarket/domain/DomainVerificationNotificationClient.java, src/test/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipControllerTest.java
1. Create new domain API's
2. Invoke API call's using oauth2 RestTemplate
2. #### Manual merge checklist:
=> PI-21919 OAuth2.0 implementations for domain verification APIs

src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
Partial revert of https://github.com/AppDirect/service-integration-sdk/pull/254
=> Reverted security config

pom.xml, src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
https://github.com/AppDirect/google-connector/pull/774
=> V2 APIs security config fix

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventClient.java, src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
Fix javadoc errors for maven javadoc plugin
=> Fixed javadoc errors

src/main/java/com/appdirect/sdk/appmarket/restrictions/context/RestrictionInfo.java, src/main/java/com/appdirect/sdk/appmarket/restrictions/context/SubscriptionInfo.java
Added SubscriptionInfo bean and updated RestrictionInfo
=> Added SubscriptionInfo bean and updated RestrictionInfo

src/main/java/com/appdirect/sdk/appmarket/restrictions/context/SubscriptionInfo.java
=> Added additional parameter for operation type in SubscriptionInfo

src/main/java/com/appdirect/sdk/vendorFields/converter/LocaleObjectConverter.java
Handling optional correctly in LocaleObjectConverter class
=> PI-23000: Handling optional correctly in LocaleObjectConverter class

src/main/java/com/appdirect/sdk/web/oauth/BasicAuthSecurityConfiguration.java, src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
Conditionally load following sdk authentication mechanism:
- Basic Auth
=> AC-563: Conditionally load sdk basic authentication configuration

Jenkinsfile
=> Added release-v1 pipeline

Jenkinsfile
=> Fixed pipeline script

Jenkinsfile
Fixed build stage for release-v1
=> Fixed build stage for release-v1

Jenkinsfile
Fixed build stage syntax issue
=> Fixed build stage syntax issue

Jenkinsfile
=> Fixed build stage

pom.xml
=> Increased staging progress timeout

Jenkinsfile
=> Removed v1 prefix

Jenkinsfile, pom.xml
Build pipeline for v1 maintenance release from `release-v1` branch  
=> Release pipeline for v1 build

README.md
Bumped up major version as updated to spring boot 2
=> Bumped up major version

pom.xml, src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java
Updated with spring managed version
=> Updated spring-hateoas version

Jenkinsfile
=> Added version prefix

src/main/java/com/appdirect/sdk/vendorFields/model/v2/Options.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorFieldsValidationRequestV2.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldV2.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java
Reverts AppDirect/service-integration-sdk#292
=> Revert "GOOG-1816: updating VendorRequiredFieldV2 payload for SDK V2 version"

src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorFieldsValidationRequestV2.java
=> dummy commit for artifact

pom.xml, src/main/java/com/appdirect/sdk/appmarket/events/OrderValidationStatus.java, src/main/java/com/appdirect/sdk/appmarket/restrictions/Restriction.java, src/main/java/com/appdirect/sdk/appmarket/restrictions/RestrictionDetails.java, src/main/java/com/appdirect/sdk/appmarket/saml/ServiceProviderInformation.java, src/main/java/com/appdirect/sdk/appmarket/usersync/UserSyncRequestPayload.java, src/main/java/com/appdirect/sdk/appmarket/validation/ValidationResponse.java, src/main/java/com/appdirect/sdk/exception/UserSyncApiErrorResponseBody.java, src/main/java/com/appdirect/sdk/vendorFields/model/VendorFieldsValidationRequest.java, src/main/java/com/appdirect/sdk/vendorFields/model/VendorFieldsValidationResponse.java, src/main/java/com/appdirect/sdk/vendorFields/model/VendorRequiredFieldsResponse.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/Suffix.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/ValidationFieldResponse.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorFieldsValidationResponseV2.java, src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldsResponseV2.java
Updated to spring boot 2.5.8 
Added no-arg constructor wherever required
=> Updated to spring boot 2.5.8 

pom.xml
NA
Upgrading spring boot version for vulnerability fix
=> VM-207: Upgrading spring boot version for vulnerability fix

src/main/java/com/appdirect/sdk/appmarket/restrictions/context/RestrictionInfo.java
Add additionalAttributes field in restrictioninfo class
=> Goog-3341 Add additionalAttributes field in restrictioninfo

pom.xml, src/main/java/com/appdirect/sdk/vendorFields/model/v3/FieldTypeV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/FlowTypeV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/VendorFieldsValidationRequestV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/VendorFieldsValidationResponseV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/VendorRequiredFieldV3.java
=> MSFT-1811 :: vendor fields v3 added

src/main/java/com/appdirect/sdk/vendorFields/configuration/VendorFieldsConfiguration.java, src/main/java/com/appdirect/sdk/vendorFields/controller/VendorFieldValidationController.java, src/main/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldController.java, src/main/java/com/appdirect/sdk/vendorFields/handler/v3/VendorFieldValidationHandlerV3.java, src/main/java/com/appdirect/sdk/vendorFields/handler/v3/VendorRequiredFieldHandlerV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/VendorRequiredFieldsResponseV3.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorFieldValidationControllerTest.java, src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java
=> MSFT-1811 :: vendor handler v3

pom.xml
service-integration-sdk version updated
=> MSFT-1811 - service-integration-sdk version updated

pom.xml, src/main/java/com/appdirect/sdk/vendorFields/model/v3/Options.java
=> MSFT-1811 :: options v3

pom.xml
version updated to generate tag
=> MSFT-1811 :: version updated to generate tag

pom.xml, src/main/java/com/appdirect/sdk/vendorFields/model/v3/OptionsV3.java, src/main/java/com/appdirect/sdk/vendorFields/model/v3/VendorRequiredFieldV3.java
optionsv3 added to vendor required field v3
=> MSFT-1811 :: optionsV3

Jenkinsfile
=> remove quotes

Jenkinsfile
=> DOPS-7464 execute script only on master

Jenkinsfile
=> Add manual approval on PR

Jenkinsfile
=> reuse node.

pom.xml
=> SDK updating nexus version

pom.xml
=> Adding jersey-json dependency for build fix

pom.xml, sonar-project.properties
Sonarqube fix : 
[MSFT-3801]: https://appdirect.jira.com/browse/MSFT-3801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MSFT-3801 upgrade spring-security-oauth2 to fix vulnerabilities
