AppDirect/service-integration-sdk

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventController.java
src/main/java/com/appdirect/sdk/web/oauth/RequestIdFilter.java
src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventControllerTest.java
src/test/java/com/appdirect/sdk/appmarket/validation/AppmarketOrderValidationControllerTest.java
src/test/java/com/appdirect/sdk/feature/RequestIdFilterIntegrationTest.java
src/test/java/com/appdirect/sdk/feature/sample_connector/minimal/MinimalConnector.java
src/test/java/com/appdirect/sdk/support/DummyRestController.java
src/test/java/com/appdirect/sdk/support/FakeAppmarket.java

Add the content of x-request-id HTTP header (if any) in MDC for all incoming requests. The used key in MDC is requestId.
JIRA ticket (https://appdirect.jira.com/browse/PI-9266):

- Added the set request id functionality for all entry points

---

src/main/java/com/appdirect/sdk/appmarket/events/EventInfo.java
src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventClientITTest.java
src/test/resources/events/subscription-order-without-links.json

Fixing: https://github.com/AppDirect/service-integration-sdk/issues/120
We ensure that the getter for the `links` field in `EventInfo` returns an empty list when the value of the field is null.

Assuming links is optional, ensuring that getLinks() returns an empty list

---

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketEventClient.java
src/test/java/com/appdirect/sdk/appmarket/events/AppmarketEventClientTest.java

Explicitly setting the accept type to JSON when fetching event. That ensures that 
https://github.com/AppDirect/service-integration-sdk/issues/123

FixedEventFetch

---

src/main/java/com/appdirect/sdk/appmarket/domain/DomainAdditionHandler.java
src/main/java/com/appdirect/sdk/appmarket/domain/DomainAdditionPayload.java
src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsOwnershipVerificationConfiguration.java
src/main/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipController.java
src/test/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipControllerTest.java
src/test/java/com/appdirect/sdk/feature/CanVerifyDomainsWhenModuleImportedIntegrationTest.java
src/test/java/com/appdirect/sdk/feature/sample_connector/full/configuration/FullConnectorDomainDnsOwnershipVerificationConfiguration.java

It should be possible to link a domain to an account.
We should have the following endpoint:
* `POST /api/v1/domainassociation/customers/{customerIdentifier}/domains`
The **Content-Type** header should be set to **application/json** and the Body should look like:
```
{
"domainName": "example.com"
}
```
No payload is expected as a response. AppMarket will use the HTTP code to determine if the operation was successful or not. The expected HTTP code for a success is `200`.
resolves #133

Adding add domain endpoint to be able to add more than one domain to an account

---

pom.xml
src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsOwnershipVerificationConfiguration.java
src/main/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipController.java
src/main/java/com/appdirect/sdk/appmarket/domain/DomainRemovalHandler.java
src/test/java/com/appdirect/sdk/appmarket/domain/DomainOwnershipControllerTest.java
src/test/java/com/appdirect/sdk/feature/CanVerifyDomainsWhenModuleImportedIntegrationTest.java
src/test/java/com/appdirect/sdk/feature/sample_connector/full/configuration/FullConnectorDomainDnsOwnershipVerificationConfiguration.java

It should be possible to remove a domain to an account.
We should have the following endpoint:
* `DELETE /api/v1/domainassociation/customers/{customerIdentifier}/domains/{domainName}`
No payload is expected as a response. AppMarket will use the HTTP code to determine if the operation was successful or not. The expected HTTP code for a success is `200`.
resolves #135

Adding remove domain endpoint to be able to remove a domain from an account

---

src/main/java/com/appdirect/sdk/appmarket/domain/DomainDnsOwnershipVerificationConfiguration.java
src/main/java/com/appdirect/sdk/appmarket/events/AppmarketCommunicationConfiguration.java
src/main/java/com/appdirect/sdk/appmarket/usersync/UserSyncConfiguration.java

JIRA ticket: https://appdirect.jira.com/browse/PI-11756
RestTemplateFactory beans were named same across different java configs, which resultsrest templates being injected into wrong places.
@hooriak

Renamed resttemplatefactory beans across all configs

---

src/main/java/com/appdirect/sdk/appmarket/events/AppmarketCommunicationConfiguration.java
src/main/java/com/appdirect/sdk/appmarket/migration/AppmarketMigrationController.java
src/main/java/com/appdirect/sdk/appmarket/migration/AppmarketMigrationService.java
src/main/java/com/appdirect/sdk/appmarket/migration/DefaultMigrationHandlers.java
src/main/java/com/appdirect/sdk/appmarket/migration/Subscription.java
src/main/java/com/appdirect/sdk/appmarket/migration/SubscriptionMigrationHandler.java
src/test/java/com/appdirect/sdk/appmarket/migration/AppmarketMigrationControllerTest.java

JIRA ticket: https://appdirect.jira.com/browse/PI-12125
Adding an endpoint for migrating subscriptions from an AppDirect marketplace to connectors. The migration process will follow the same procedure as regular marketplace migrations, but an extension is expected to **validate** (via the validation endpoint) and **dispatch** the subscription payload to the correct connector.

Adding subscription migration endpoint

---

src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrder.java
src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java
src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParserTest.java
src/test/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderTest.java

Until now there has not been a connector that requires add-ons. We need to get the parentAccountIdentifier from the AccountInfo in order to process an Add-On purchase in Microsoft
JIRA ticket: [PI-12313](https://appdirect.jira.com/browse/PI-12313)

PI-12313 Adding AccountInfo to SubscriptionOrder.

---

src/main/java/com/appdirect/sdk/web/oauth/SecurityConfiguration.java
src/main/java/com/appdirect/sdk/web/oauth/model/OpenIdCustomUrlPattern.java
src/test/resources/application.yml
src/test/resources/logback-test.xml

Introduce `openid.secured.url.patterns` property configuration to be able to configure a list of custom pattern that should be secured.
resolves #161

Introduce `openid.secured.url.patterns` property configuration to be able to configure a list of custom pattern that should be secured.

---

src/main/java/com/appdirect/sdk/vendorFields/controller/VendorFieldValidationController.java
src/test/java/com/appdirect/sdk/vendorFields/controller/VendorFieldValidationControllerTest.java

- Fix `VendorFieldsValidationController` where InitBinder was missing provoking error parsing Locales. Added UTs to prevent this from happenning

Added InitBinder for VendorFieldValidationController and added UT for it

---

src/main/java/com/appdirect/sdk/vendorFields/converter/LocaleConverter.java
src/test/java/com/appdirect/sdk/vendorFields/converter/LocaleConverterTest.java

- `Locale.forLanguageTag()` is not validating if the parameter is valid. Therefore, we need to manually iterate over all available locales and validate if the locale is valid (otherwise drop it).

Fixed bug in Locale jdk where Locale is created with invalid tag. Filtering out values with invalid locale

---

src/main/java/com/appdirect/sdk/meteredusage/model/UsageItem.java
src/test/java/com/appdirect/sdk/meteredusage/mother/UsageItemMother.java
src/test/java/com/appdirect/sdk/utils/ConstantUtils.java

The field eventDate was added to metered-usage service API contract.
The field eventId was added to metered-usage service API contract

PI-16557/16556: Added eventId and eventDate to usageItem

---

pom.xml
src/main/java/com/appdirect/sdk/meteredusage/model/UsageItem.java

- `eventDate` is being serialized as an object (with `dayOfMonth`, `year`, `calendar`, etc). This PR fixes the serialization.

Fixing eventDate serialization for UsageItem

---

src/main/java/com/appdirect/sdk/meteredusage/model/UsageItem.java
src/test/java/com/appdirect/sdk/utils/ConstantUtils.java

- Reformat eventDate to 2019-10-23T09:39:12.569Z or similar. In order to achieve that, we need to store the ZoneId in the entity, therefore we need a ZonedDateTime for it.

PI-16726: Reformat eventDate to 2019-10-23T09:39:12.569Z or similar

---

pom.xml

- There is an error in one of the services using the AppDirect Libraries that are using an older version from Zipkin, provoking the service to not boot. `5.6.9` decreased into `5.1.0`.
- Result from `mvn dependency:tree`.
_In the SDK_
```
[INFO] |  +- io.zipkin.brave:brave-instrumentation-okhttp3:jar:5.6.9:compile
[INFO] |  |  +- io.zipkin.brave:brave-instrumentation-http:jar:5.6.9:compile
[INFO] |  |  \- io.zipkin.brave:brave:jar:5.6.9:compile
[INFO] |  |     +- io.zipkin.zipkin2:zipkin:jar:2.15.0:compile
[INFO] |  |     \- io.zipkin.reporter2:zipkin-reporter:jar:2.10.0:compile
```
_In the AppDirect Library_
```
[INFO] |  +- com.appdirect.boot:appdirect-boot-tracing-core:jar:0.3.4:compile
[INFO] |  |  \- io.zipkin.reporter2:zipkin-sender-okhttp3:jar:2.7.3:compile
[INFO] |  +- …
```

Change zipkin version to be the same used by appdirect

---

src/main/java/com/appdirect/sdk/security/encryption/configuration/EncryptionConfiguration.java
src/main/java/com/appdirect/sdk/security/encryption/service/AESEncryptionServiceImpl.java

To be able to use EncryptionService on the Connectors, it must be included as part of the Configuration class that will allow the service's instantiation.

PI-16962: Added EncryptionService as part of the EncryptionConfiguration class

---

src/main/java/com/appdirect/sdk/meteredusage/model/MeteredUsageItem.java
src/test/java/com/appdirect/sdk/meteredusage/mother/MeteredUsageItemMother.java
src/test/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceTest.java
src/test/java/com/appdirect/sdk/utils/ConstantUtils.java

This PR adds a subscriptionId field to the MeteredUsageItem class to account for changes in Metered Usage API. It's been annotated not to get serialized into Json when its null, to avoid breaking flows that don't need it. 

PI-17602 Add subscriptionId field to MeteredUsageItem

---

src/main/java/com/appdirect/sdk/meteredusage/model/MeteredUsageItem.java
src/test/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientServiceTest.java

This PR adds a constructor to the MeteredUsageItem class with only the fields it used to have, in order not to break clients that were using older versions of it.

PI-17602 FIX: Backwards compatibility for MeteredUsageItem

---

pom.xml
src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java

Fixed issue in the SDK that caused MP event to failed due to old dependency version.

PI-17312: Updated hateos version and fix SubscriptionOrderEventParser issue

---

pom.xml
src/main/java/com/appdirect/sdk/appmarket/events/SubscriptionOrderEventParser.java

Changed SubscriptionOrderEventParser error handling.

PI-17312: Changed SubscriptionOrderEventParser

---

src/main/java/com/appdirect/sdk/appmarket/events/FreeTrialInfo.java
src/main/java/com/appdirect/sdk/appmarket/events/OrderInfo.java

N/A
Adding FreeTrialInfo class in OrderInfo to support G suite free trial as per https://appdirect.jira.com/wiki/spaces/PI/pages/1108542589/TD+PI-18513+-+G+Suite+Free+Trial

PI-18691: adding FreeTrialInfo class to OrderInfo

---

src/main/java/com/appdirect/sdk/meteredusage/service/MeteredUsageApiClientService.java

When Usages are already reported to MUV2 we get 400 error having idempotency key error. We should not make a retry again to report Usages if they are already reported.

Exclude MeterUsageServiceException from retryable

---

src/main/java/com/appdirect/sdk/vendorFields/model/Context.java
src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldsResponseV2.java
src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java

Add Context to VendorRequiredFieldsResponseV2 as we need to have the option to return context so that RFS and determine whether to return item-level or cart-level to the UI

PI-20330 Add Context to VRF response

---

src/main/java/com/appdirect/sdk/appmarket/validation/AppmarketOrderValidationController.java

With Checkout V2 flow, When the PRF fields are having empty values, empty requestBody is sent to validation endpoint(/unsecured/integration/orderValidation).
Making RequestBody optional for this endpoint.

PI-21145  : Making request body as optional for Order Validation

---

pom.xml

SDK Jenkins build is failing for SDK tag
Updating SDK version to 122
Git::GitExecuteError: git '--git-dir=/var/****/workspace/service-integration-sdk-0/.git' '--work-tree=/var/****/workspace/service-integration-sdk-0' tag '1.121' '-m Tag for 1.121'  2>&1:fatal: **tag '1.121' already exists**
https://pi.ci.appdirect.tools/job/service-integration-sdk-release-dsl/109/console

Updating SDK version

---

src/main/java/com/appdirect/sdk/web/oauth/BasicAuthSecurityConfiguration.java

We need to disable csrf check for basic security configuration
As was getting 403 for domain association apis
###Dev Testing

PI-22232 Disable csrf check for basic security configuration

---

src/main/java/com/appdirect/sdk/vendorFields/model/v2/Options.java
src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldV2.java
src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java

NA
Inorder to send message to RFS from connector instead of messageKey need to update VendorRequiredFieldV2 payload 
as per https://appdirect.jira.com/browse/PI-23580

GOOG-1816: updating VendorRequiredFieldV2 payload 

---

src/main/java/com/appdirect/sdk/vendorFields/model/v2/Options.java
src/main/java/com/appdirect/sdk/vendorFields/model/v2/VendorRequiredFieldV2.java
src/test/java/com/appdirect/sdk/vendorFields/controller/VendorRequiredFieldsControllerTest.java

NA
Inorder to send message to RFS from connector instead of messageKey need to update VendorRequiredFieldV2 payload 
as per https://appdirect.jira.com/browse/PI-23580

GOOG-1816: updating VendorRequiredFieldV2 payload for SDK V2 version
